### PR TITLE
Simplify with newtypes

### PR DESCRIPTION
**Pull request by LeanderK**
opening new pull-request to start things clean.
Please see #76 for background:

I have ticked every task I have thought about, but if you don't agree just let me know.

tasks from the old pull-request:
- [X] rename Addition/Multiplication
- [ ]  move to production-level via 1. compiling, 2. -Wall, 3. full haddock coverage, 4. consistent styling
- [X]   coding style as per hindent (open to other suggestions) (I used brittany because of HIE)
- [X]   comb ==> magma
- [ ]   drop plus completely, and go for (+) as the magma. ditto times
- [ ]  coerce naming convention: U unary, B binary, T ternary, rather than ' etc.
         I am thinking about dropping coerce entirely. Since GHC 8.6 and `deriving via` is right around the corner we probably won't need it afterward
- [X]   neg ==> negate
- [X]   Semiring: Unital (Add a) redundant?
          No, a Semiring drops only the requirement for an Additive Inverse

Questions/Discussion
- [X]   *exporting Semigroup will conflict with every code base in existence, and you have to export if peeps need to constrain. ==> Associative
          + avoid Monoidal entirely* see below
- [X]   *Hadamard: why is this Linear?*
           Hadamard-Multiplication is part of the linear-algebra
- [ ]   QuotientField to Integral module(???)
- [ ]   where would Integral go in a heirarchy. Very difficult to place.
- [ ]   NumHask.Data.Positive is a great test bed for future development
- [X]   *There is only AbelianGroup (Add a) and no references to a AbelianGroup (Mult a). Why?*
         I don't really understand this question. `AbelianGroup` i just way more common, because commutativity is one of the defining features of addition very often required (not many multiplications are commutative!). But nobody stops you from having a AbelianGroup (Mult a)-constraint.
- [X]   *Addition: Associative, Commutative Multiplication: Absorbing, Associative, Unital. Really? Let's discuss and R&D why this is so asymmetric.*
        It's the defining characteristics of Addition and Multiplication. If they weren't asymmetric, there would be no use of having two operations and we would not have the newtype-problem. In Math, Multiplication has a broader usage (it essentially replaces the magma-operation). But, since we had our addition-discussion, I opted for a more specific properties. Absorbing is very important, because it can't be derived from plus. See https://en.wikipedia.org/wiki/Multiplication#Axioms as the construction of multiplication in the peano-axioms. But I am open for discussion of adding/dropping some constraints.
- [X]   *Absorbing is very tricky in terms of placement. Note that the rule references a concept that only occurs well up (down?) the tree, in Multiplication. Maybe it's better there.*
          I don't think that's a great idea. The point of this pull request is to have a clear divide between properties and resulting structures. Nobody stops you from defining an absorbing element fro the addtion, which might have some usage.
- [X]   *Module - alternative name?* See below
- [ ]   Is Abstract a necessary part of the naming heirarchy? (Adding up stuff is the opposite of abstract, nevermind it's the correct term for maths)
- [X]   *Singleton - I use this often. Where in the heirarchy would a hom :: a -> f a go? In Module module?*
           Hmm, i am not sure. Probably.
- [X]  * do coerces need exporting? I hope not.*
         thinking of getting rid of them.
- [X]   *Homomorphism isn't connected to any other module. Purpose?*
          Homomorphisms are a very fundamental part of Algebra, so I thought I would put this in there.
- [X]   *IntegralDomain to Field module*
         IntegralDomain is usually considered to be part of the ring-hierarchy, at least that's what I was taught. But I don't really care.
- [ ]   drop Natural until we're back to production

### CODE REVIEW

**Comment by LeanderK** [comment]
quick note: I like to squash commits only at the last second and not while developing the pull-request. But it's on my radar

**Comment by LeanderK** [comment]
I want to start the discussion of a very important issue:

**What to with the names!**

There are currently multiple naming-related issues. For example: `Module - alternative name?` and the `Semigroup/Monoid` problem. 

I want to first address the idea of really renaming stuff (Module, Hilbert-, Banach-space). I don't think it's a good idea to redefine mathematics, because they are also really accepted and well-developed concepts. Also, it makes it harder to understand what they are about and rips communities apart. If you google Ring, you arrive at Wikipedia with a complete definition, examples etc. Everything needed to understand them is here: https://en.wikipedia.org/wiki/Ring_(mathematics). Note that even non-mathy mainstream haskell uses the basic mathmatical concepts (Semigroup, Monoid, Monad, Functor etc.) and doesn't redefine them. I think more advanced (and in numhask simplified concepts) can be expressed otherwise, maybe banach & hilbert-space?

But one thing makes me more headaches and worries me. I thought about it and really think we should redefine `Semigroup/Monoid`. Why? It makes the whole hirarchy easier to work with! We can express things as Monoids and have them work as expected. I would also add `Quasigroup` and `Loop`, they come up sometimes. As an alternative, I would just completely drop them and use `Semigroup/Monoid` from Prelude. (Which would require overlapping instances...because they overlap). What we are doing with `numhask` is not replace `Num`, but replace the `Algebra`-stuff in prelude! Addition/Multiplication are only instances!

**Comment by tonyday567** [comment]
It's all looking pretty good to squish and getting some collaboration refactoring going.  All my other libraries rely on numhask, so we get a lot of concrete feedback on api changes in trying to get these working for the new structure.

> nevermind it's the correct term for maths

I think this is fundamental.  I think that the correct term for coding trumps the correct term for maths.  The first refactor I'd do is drop Abstract from the naming hierarchy.

> Addition: Associative, Commutative Multiplication: Absorbing, Associative, Unital

The main thing that stands out is no Unital for addition.  Once we get the library stabilised, producing a graph of the heirarchy becomes very useful in finding constraints to eliminate.

Regardless of where we land on current major issues, I suggest we squish and PR to `refactor`, so I can start testing the api.

**Comment by LeanderK** [comment]
> > the goal of numhask should be to provide a reasonable basis for math

> Maybe, but that's a bit narrow. It's also meant to be a reasonable base for coding in haskell with numbers, which I think is wider than just doing maths. And to do that, numhask needs to fit in with existing haskell practices.

I have a very broad definition of math...essentially everything that involves axioms, logic etc. and not only numbers, which you could argue haskell fits into 🙂 

@tonyday567 Ok, so what should I do with Monoid/Semigroup? They are very important constructs and needed for a lot of Algebraic Structures. I think the resistance is too great to introduce them into numhask, but I am not sure what the alternative you are proposing is. instances for the base-class? `Monoidal` +  `Semigroup` to `Associative`? If it's just renaming, then I am okay with it, though I don't really see the point because you can alway import `base` or `Numhask` as qualified. But okay...bikeshedding is always a problem.

**Comment by tonyday567** [comment]
> I squashed, rebased, confused the branches and pushed the wrong stuff overwriting my changes 😉 Thanks to git reflog everything should be fine now!

Can't recall a squash where that didn't happen.

**Pull request merged**
