### PR TITLE
Fixed wrong behaviour in Rational

### PR DESCRIPTION
**Pull request by LeanderK**
This pull request addresses #51.
Took surprisingly long to find the culprits.

I think I fixed the round-breakage, but the tests are failing. The funny thing is that I can't reproduce it in ghci. I will look at it again tomorrow, maybe I am too tired.

### CODE REVIEW

**Comment by LeanderK** [comment]
travis fails with:
```haskell
round a == floor (a + one/(one+one)):                             FAIL
            *** Failed! Falsifiable (after 7 tests):
            (-5) :% 2
```

but
```haskell
> let x = (-5) :% 2
> NumHask.Algebra.round x
-2
> NumHask.Algebra.floor (x + one/(one+one))
-2
> NumHask.Algebra.round x == NumHask.Algebra.floor (x + one/(one+one))
True
```
what am I missing?

**Comment by ocramz** [comment]
@LeanderK @tonyday567 ^ looks like a bug to me

**Comment by tonyday567** [comment]
bankers rounding.  http://wiki.c2.com/?BankersRounding

The test is wrong.  

```
if even (a + one/(one+one)) then (round a == floor (a + one/(one+one))) else (round a == floor (a - one/(one+one)))
```

**Comment by tonyday567** [comment]
https://github.com/tonyday567/numhask/blob/master/numhask/src/NumHask/Algebra/Field.hs#L133 for the gory details

**Comment by tonyday567** [comment]
OMG, that bool switch was a terrible bug.  thanks!

**Comment by LeanderK** [comment]
Ah, I wanted to write that I think your 
```
if even (floor (a + one/(one+one))) then (round a == floor (a + one/(one+one))) else (round a == floor (a - one/(one+one)))
```
was slightly wrong. I have implemented `ceiling (a - one/(one+one))` (reason: the rounding is the opposite, check it youself for `-(1/3)`, which should round to `0`, but `floor (-(1/3)-1/2))` evaluates to `-1` ).

**Comment by tonyday567** [comment]
Of course, yes.  I've come to respect the tests as the important bits.

**Pull request merged**
