### PR TITLE
Fixed Module operators

### PR DESCRIPTION
**Pull request by tonyday567**
#158

### CODE REVIEW

**Comment by duairc** [comment]
Thanks for implementing this! I'm not sure if I would have removed all the other operators from their type-classes; it can be nice to be able to override some their definitions for efficiency's sake. I can understand keeping only one of `*.` and `.*` because the library generally assumes that multiplication is commutative. If you're bothered by the inconsistency of `/.` and `-.` being defined in terms of `negate` and `recip` but `/` and `-` not, then you could add them back to `MultiplicativeAction` and `AdditiveAction` respectively:

```haskell
class Additive a => AdditiveAction m a | m -> a
 where
  (.+) :: a -> m -> m

  (-.) :: Subtractive a => m -> a -> m
  m -. a = negate a .+ m


class Multiplicative a => MultiplicativeAction m a | m -> a
 where
  (.*) :: a -> m -> m

  (/.) :: Divisive a => m -> a -> m
  m /. a = recip a .* m
```

**Comment by duairc** [comment]
In fact, I have an instance of `QuotientField` where the types are not instances of `Ord`, so I would no longer be able to use `round`, `truncate`, etc with these changes, which is pretty important to me.

**Comment by tonyday567** [comment]
Ok, I'm following https://github.com/haskell/core-libraries-committee/issues/3, and guessing that single method classes provide some boost in performance. Single methods are much neater from theoretic stand-points as well.

But, yes, I got carried away.  Will revert the QuotientField and ExpField ones.

I like the right scalar actions as separate operators - as you say, they are different to the left ones.

Thinking about (-) and (/) ...

**Comment by duairc** [comment]
I really think `-` and `/` should be part of the class. For example, consider the `Subtractive` instance for `Natural`. I know it's kind of dodgy anyway, but at least it's at least useable as long as certain preconditions are met. But with this change, it's useless, because `negate` will always error.

**Comment by tonyday567** [comment]
ok, yes.  Will go for the mutuals:

```
negate a = zero - a
a - b = a + negate b
```

**Pull request merged**
