### PR TITLE
WIP: Radically simplify

### PR DESCRIPTION
**Pull request by tonyday567**
Unhooking the hierarchy from Sums, Products, Magmas and whatnot sure makes things cleaner, and removes the inference problems.

I'm coming around to Eds view:

"Haskell, as currently designed is good at dealing with a few well-chosen levels of abstraction. It isn't actually terribly good at dealing with very deep accurate typeclass hierarchies."

https://www.reddit.com/r/haskell/comments/4ka6wz/typeclasses_with_multiple_functions/

See NumHask.Data.Wrapped for the deriving characteristics, which seem neat.

### CODE REVIEW

**Comment by LeanderK** [comment]
Well...for me, this PR wipes out the whole point of the library, or at least my motivation.

I think the whole point is a better, more general representation of the numerical hierarchy. If we remove the critical bit, I think there's much complexity, but no real gains left. I think the group hierarchy is critical.

I know Haskell isn't super awesome at this yet. I would also fully expect some inference issues. But If we move into higher dimensions, some operations lose certain laws and the mathematical structures and their interactions just get complicated (including concepts like inverse, pseudo-inverse, determinants, pseudo-determinants). Building structures that let you reflect these things in the type-system were sort of my goal. Normal numbers are easy because they mostly follow intuition and I agree that we are building something very complicated just to add 2 ints. But I always had in mind that we not only want to add Ints, but also matrices, tensors and everything in between.

I wonder whether it's possible to build 2 compatible (!) libraries or layers that gradually introduce complexity since there are clearly different view what this library should strive for.

**Comment by tonyday567** [comment]
I hear you!  In my heart of hearts, I believe that knowing the exact laws that apply to a given computation gives you the ultimate fusion roadmap, one that can't be bettered by another system.

But inference is a show-stopper for adoption.  Being able to supply a one-liner interface where the user can choose laws and operations, as simple as `newtype MyNumber a = MyNumber a deriving (Addition, Subtraction, Multiplication, QuotientField) via Wrapper` feels like a big win.  This also looks impossible for haskell right now, if we stick with the `Sum` `Product` methods.

Unless I'm doing something unusual, I don't want the Sum/Product boiler-plate in my face all the time when working on higher-kinded numbers.  It's also very easy to learn the constraints needed as well: if it has a `(-)`, then it needs a Subtractive constraint etc. It also seems that a more fine-grained hierarchy cannot be hidden from the user, and practice and the compiler suggests strongly that any hiding creates fragility in the code upstream. 

It seems then, that this design decision is very real and needs to be made.

**Comment by LeanderK** [comment]
Why is `newtype MyNumber a = MyNumber a deriving (Addition, Subtraction, Multiplication, QuotientField) via Wrapper` not possible otherwise? It even works with just GND. I have code in another repo that does the exact thing via GND.

what do you mean with `Sum/Product`boiler-plate?

**Comment by tonyday567** [comment]
See https://gist.github.com/tonyday567/71a2d02dcf14893174517f006b729866#file-basics-hs-L88

It looks like you can't say `newtype A a = A a deriving (Magma (Sum a))`

**Pull request merged**
