### PR TITLE
first try at simplifying the hierarchy

### PR DESCRIPTION
**Pull request by LeanderK**
## 1.st try: Addition as the default superclass magma
It's getting late, I will work on this and provide a better motivation tomorrow. **Work in progress!**

Changes:

- moved `Additive` into `Group`, deleted `Magma`
   - `Group` is, in my opinion, the more intuitive name for this class, since we usually classify these things as group-like in abstract-algebra
  - this eliminates the whole `Additive` - hirarchy, saving half of the cognitive overhead. Why Additive and not Multiplicative? Usually, additions generalize better than our intuition of Multiplications (since it requires less laws, no annihilation etc.) and is commonly more generally defined. In my experience, it's wider used to represent abstract operations than multiplication.
   - removed `Left/Right-Cancellative`. Is there any justification for these? We are also skipping other algebraic structures and I think they are equally unmotivated and are only adding noise to the hirarchy.
- moved `Multiplicative` into `Ring`
  - a common definition of `Multiplication` is done via `Ring`

- introduce a few common names via the class/instance trick

Why is this more intuitive?
It introduces the additive/multiplicative in their defining algebraic structures and not separate. We also now have a default for a more principled `Group`-structure, which is very fundamental for many applications.

I will probably get something compilable tomorrow. There are also instances and some classes missing.

### CODE REVIEW

**Comment by tonyday567** [comment]
Privileging Addition as the semigroup instance for numbers has been thoroughly rejected by the Haskell community, with the equally-ranked Sum and Product monoids as witnesses.
I used to argue, similar to the above, that addition is special versus multiplication and the natural semigroup instances, but I've since changed my mind via getting numhask together.  I came around to the compsci theoretic point of view that there is nothing special about addition until you can point to the specialness in a law.  And that seems to happen around distribution of (*) over (+) where the order of the operators start to matter.

The library avoids Semigroup and Monoid to not clash with base, hence the use of Associative for Semigroup and Monoidal (though Monoidal is not used upstream and I think we should ditch it).

More generally, I find the rearrangement makes it all more confusing for me.  It might a different perspective that a coder brings versus a mathsy perspective.  Some confusions include:
- why isn't zero defined as the Additive unital, and needs a MultiplicativeMagma to exist?  I like having an Absorb class for the law but I had thought it belongs more in Distribution?
- IntegralDomain seems to come out of nowhere.  Is it somewhat like Cancellative for multiplication?  Is it just for Integrals?
- MagmaCompat and coerce adds to complexity for the sake of starting with a single magma.  I think you either go the gaia head-on coerce route, or have two magmas (disconnected from the foundational magma definition).

Magma.hs is (was) there solely for documentation purposes but this may add to the confusion.

We want to be able to fit in with existing Haskell practices, and this has solidified around:
- Semigroup as representative of an associative magma (without splitting just the magma out)
- Monoid as representative of a unital magma + semigroup
- use of Sum and Product wrappers to distinguish between the two magmas.
- not yet solid, but this also exists: https://github.com/ekmett/abelian/blob/master/src/Control/Commutative.hs

I think this all makes the design decision a difficult one.  We dare not trample on existing usage, and the privileging of addition gets up many noses.

But I'm biased by my priors and experience, and am not exactly sure what the cognitive load is that is being reduced.  A binary operator aka magma plus 4 laws add up to a Group, and we throw idempotence in, just because it's way cool.  We add the prefix of Additive and Multiplicative to distinguish the two operators/magmas that commonly form an algebra, and we use Associative instead of Semigroup and avoid Monoid to avoid clashes with base. What can go wrong ;-P

**Comment by LeanderK** [comment]
These are valid points and I think my current proposal doesn't address it.
I will update this later...

**Comment by LeanderK** [comment]
This is just a proposal and an Idea of how to improve the current state. I hacked it together in a few hours and more of a prototype than a finished hierarchy. But I will try to motivate it a bit more and address some of your concerns (i have a lot to do today, so expect more tomorrow). Some of your concerns are just existing because this is a very rough draft, that I have mostly moved stuff around.

## Motivation
Usually, in mathematics, addition and multiplication don't fall out of anything, like the `magma`, but arise due to construction. The Idea is that there are laws and structures, which define what an addition and what a multiplication is. The philosophy of the reworked hierarchy is to follow this construction and place the addition and multiplication in their defining algebraic structures. There are a few different ways to define addition and multiplication, but they're more or less the same. I have opted for the more general.
That's why talking about an AdditiveMagma is kind of weird, because there is nothing additive about a magma.
A defining property of the Addition is that it is commutative, from integer, to vector, to matrix-addition, it's always commutative. So one option, which I have opted for, is to define Addition and it's `(+)` as an commutative semigroup (another common would be the abelian group).
A common definition of multiplication is as the second binary operation in `Ring`, that's why I've placed the Multiplicative-Definition there (there are others via the absorbing-property, which i think we should use). I was just copying definitions and did some quick adjustments. It is not ready for a detailed critique of the definition of Multiplication.

One, I think very important, distinction to the current hierarchy is that the ring and the group are the fundamental parts and not the Multiplication and the Addition. This is in line with the rest of Haskell, where Semigroup, Monoid etc. are very commonly used. I thought about resuing them from Base, but I think redefining makes the whole hierarchy simples and more principled. We can define an Isomorphism via instances. I think this is the most important distincition and makes it easier to to resolve the difference between numeric types and abstraction we use for other parts of the language (monoid instances for various data-structures). They are really the same, there's just one semigroup/monoid etc. and addition/multiplication can be defined using these abstractions.

## Your concerns

 - > Privileging Addition as the semigroup instance for numbers has been thoroughly rejected by the Haskell community, with the equally-ranked Sum and Product monoids as witnesses.
   - well, I can make it explicit. I can whip up a second proposal with a slight derivation. But it always bothered me 😀 But I don't think it has been "thoroughly rejected", at least I don't find a great backslash in searching for it.
- > I came around to the compsci theoretic point of view that there is nothing special about addition until you can point to the specialness in a law. And that seems to happen around distribution of (*) over (+) where the order of the operators start to matter.
  - that's true for simple numbers like reals, but we loose the commutativity pretty fast. Multiplication for Quaterions is not commutative and so is matrix-multiplicaiton. A commonly used difference to Addition is the property of 0 (the existence of an absorbing element). I have not reflected that yet in my proposal...wait and see 😉
 - > The library avoids Semigroup and Monoid to not clash with base, hence the use of Associative for Semigroup and Monoidal (though Monoidal is not used upstream and I think we should ditch it).
    - I think this is the more serious drawback of the current hirarchy. There is really no difference between those two definitions of monoids and semigroups. We should either opt for defining them on our own and adding instances for `base`, or using the one from `base`.
- >More generally, I find the rearrangement makes it all more confusing for me. It might a different perspective that a coder brings versus a mathsy perspective. Some confusions include:
     why isn't zero defined as the Additive unital, and needs a MultiplicativeMagma to exist? I like having an Absorb class for the law but I had thought it belongs more in Distribution?
IntegralDomain seems to come out of nowhere. Is it somewhat like Cancellative for multiplication? Is it just for Integrals?
   MagmaCompat and coerce adds to complexity for the sake of starting with a single magma. I think you either go the gaia head-on coerce route, or have two magmas (disconnected from the foundational magma definition).
    - I have not changed the names much yet and just copied the definitions. I will try to get better names. 
   - Distribution is just the distributive property and should be indipendent from the absorbing element.
   - I can improve the motivation and the laws for `IntegralDomain`, it's sort of key law that we need for division. Maybe it's a bit useless here, I can always delete it. But it also popped up in gaia!
   - reg. MagmaCompat and coerce: I think I can improve the multiplication-hirarchy, it was more or less copied and recude the usage of MagmaCompat and coerce. I think a better name would also make it easier. But keep in mind that it's only needed to get the Monoid/Semigroup/Magma instances for multiplication.

**Comment by LeanderK** [comment]
I will answer some of your concerns later, I absolutely take them seriously! 🙂
If the "default" magma instance for addition is the one thing that's bothering you the most, I can whip up a second proposal using either associated types like in Gaia or newtypes.

**Comment by tonyday567** [comment]
No need to rush through this that I can see, so let's aim for clarity versus speed.

> That's why talking about an AdditiveMagma is kind of weird, because there is nothing additive about a magma.

I don't see the weirdness.  (+) is a closed binary operator, and so can be a magma, and we just name it 'Additive' to distinguish it from other magmas like multiplication.  Your reading is like "instance Additive Magma"

> A defining property of the Addition is that it is commutative, from integer, to vector, to matrix-addition, it's always commutative.

Strings aren't commutative, so this design decision would exclude using (+) for string concatenation. It seems unnecessary to make this exclusion.

> A common definition of multiplication is as the second binary operation in Ring

So the existing code defines multiplication as an operator (*) on a domain that satisfies the unit and associativity laws.  Introducing motivations like maths constructions and Ring theory into the definition seems unnecessary and fuzzy.

This might be the nub of the issue - coders do not need to know what a Ring is to understand multiplication.

**Comment by JamieBallingall** [comment]
I've been trying to familiarize myself with this library and experiencing the cycle of "Wait! That's weird ... Oh! I see". So I thought I would add my perspective.

I found `AdditiveMagma` and `MultiplicativeMagma` intuitive and unobjectionable. I read `AdditiveMagma` as "Magma with it's binary operation written as +" or "Magma under addition".

**Comment by LeanderK** [comment]
yeah..i am also not really satisfied with the solution

**Comment by LeanderK** [comment]
@JamieBallingall what do you think of #76 ?

**Comment by JamieBallingall** [comment]
@LeanderK I don't know. It's clearly a major reworking of the library. I get the sense that @tonyday567 and others have put significant thought into the current structure and so I am nervous of radical changes but I don't know enough about the current state of the library or abstract algebra as a topic to evaluate it on its merits.

**Comment by ocramz** [comment]
@LeanderK @JamieBallingall yeah it will take me a while as well to digest the nature of these changes.

**Comment by LeanderK** [comment]
I think #76 is way superior to #75

**Pull request closed without merging**
