### PR TITLE
add NumHask.Data, addresses #49

### PR DESCRIPTION
**Pull request by ocramz**
* Sum
* Product

Added just the basic instances

### CODE REVIEW

**Comment by ocramz** [comment]
Purely chasing definitions, we should have `AdditiveAssociative a => Semigroup a where { (<>) = plus}`, etc. no?

**Comment by ocramz** [comment]
I think so; shouldn't they be something like

```
instance AdditiveAssociative a => Semigroup (Sum a) where
  (Sum x) <> (Sum y) = Sum (x `plus` y)
```

?

**Comment by tonyday567** [comment]
Yes.  And can you just use coerce for <*>?

**Comment by ocramz** [comment]
Will do ! Though I don't understand at all why is `coerce` needed. As in, we need something of type say `Sum (a -> b) -> Sum a -> Sum b`

**Pull request merged**
