### PR TITLE
added function (a -> b) instances

### LINKED ISSUE #50: (->) instances
Create instances for (->)

### PR DESCRIPTION
**Pull request by LeanderK**
this fixes #50 

pretty excited about these, I think they could come in handy!

### CODE REVIEW

**Comment by tonyday567** [comment]
Looks good to me! +1

**Comment by tonyday567** [comment]
Am very happy for you to hit the button with non-structural PRs such as this.

**Comment by LeanderK** [comment]
ah ok, I am used to the convention of reviewers being the only ones who can merge stuff

**Comment by tonyday567** [comment]
It's a good convention, but I think we are in a spot somewhere between exploring the design space and in production.  I'm really wanting to push the library into good shape pretty quickly.

**Pull request merged**
